---
jobs:

#############################
#Set PR Status to Pending
#############################
- name: Set-PR-status-to-pending
  public: true
  plan:
  - get: ui
    resource: ui-pr
    trigger: true
    version: every
  - get: ui-original-pr
    resource: ui-pr
  - put: ui-pr
    params:
      path: ui
      status: pending
      context: PR-Gate

#############################
# Do UT
############################

- name: UI-Unit-Test
  public: true
  plan:
  - get: ui_ut_container
# Get PR repo with new local folder named "ui"
  - get: ui
    resource: ui-pr
    passed: [ Set-PR-status-to-pending ]
    trigger: true
    version: every
    params:
      fetch_merge: true
# Run UT task
  - task: unit-test 
    image: ui_ut_container
    file: ui/ci/unit-test.yml
    on_failure:
      do:
        - get: ui-original-pr
          resource: ui-pr
        - put: ui-pr
          params:
            path: ui-original-pr
            status: failure
            context: PR-Gate

#############################
# Do e2e Test
############################

- name: UI-e2e-Test
  public: true
  plan:
  - get: ui_ut_container
# Get PR repo with new local folder named "ui"
  - get: ui
    resource: ui-pr
    passed: [ Set-PR-status-to-pending ]
    trigger: true
    version: every
    params:
      fetch_merge: true
# Run UT task
  - task: e2e-test
    image: ui_ut_container
    file: ui/ci/e2e-test.yml
    on_failure:
      do:
        - get: ui-original-pr
          resource: ui-pr
        - put: ui-pr
          params:
            path: ui-original-pr
            status: failure
            context: PR-Gate




############################
# Test AOT Build
###########################

- name: UI-AOT-Build
  public: true
  plan:
  - get: ui_ut_container
# Get PR repo with new local folder named "ui"
  - get: ui
    resource: ui-pr
    passed: [ Set-PR-status-to-pending ]
    trigger: true
    version: every
    params:
      fetch_merge: true
  # Run AOT Build
  - task: build-aot
    image: ui_ut_container
    file: ui/ci/build-aot.yml
    on_failure:
      do:
        - get: ui-original-pr
          resource: ui-pr
        - put: ui-pr
          params:
            path: ui-original-pr
            status: failure
            context: PR-Gate

#############################
# Feedback to PR status
#############################
- name: Set-PR-Result-Status
  public: true
  plan:
  - get: ui
    resource: ui-pr
    trigger: true
    version: every
    passed:
    - UI-Unit-Test
    - UI-e2e-Test
    - UI-AOT-Build
  on_success:
      put:  ui-pr
      params:
        path: ui
        status: success
        context: PR-Gate
  on_failure:
      put: ui-pr
      params:
        path: ui
        status: failure
        context: PR-Gate



resource_types:
- name: pull-request
  type: docker-image
  source:
    insecure_registries:
    - {{local-registry}}
    repository: {{local-registry-repo-pr}}

resources:
- name: ui_ut_container 
  type: docker-image
  source:
    repository: {{local-registry-repo-ut}}
    insecure_registries:
    - {{local-registry}}
    tag: latest

- name: ui-pr
  type: pull-request
  source:
    repo: {{github_repo}}
    skip_ssl_verification: true
    uri: git@eos2git.cec.lab.emc.com:{{github_repo_owner}}/rackhd-ui-2.0.git
    access_token: {{eos2github-token}}
    api_endpoint: https://eos2git.cec.lab.emc.com/api/v3
    base: master
    private_key: {{eos2github-private-key}}
